using System;
using DosinisSDK.Core;
using UnityEngine;

namespace DosinisSDK.Vfx
{
    public interface IVfxManager : IModule
    {
        long PlayAtPoint(IVfx vfx, Vector3 point, Vector3 forward, AudioClip sfx = null, Action done = null);
        
        /// <summary>
        /// Returns VFX hash for further control
        /// </summary>
        /// <param name="vfx">Source VFX used for pooling</param>
        /// <param name="forceKeepOrientation">Force local rotation to identity?</param>
        /// <param name="parent">Override parent</param>
        /// <param name="sfx">Sound effect</param>
        /// <param name="offset">Offset from parent</param>
        /// <param name="done">Callback when vfx is no longer alive</param>
        /// <returns></returns>
        long Play(IVfx vfx, bool forceKeepOrientation = true, Transform parent = null, AudioClip sfx = null, Vector3 offset = default,
            Action done = null, bool forceKeepLocalOrientation = false);
        
        bool IsPlaying(IVfx vfx, long key);

        /// <summary>
        /// Stops the provided VFX
        /// </summary>
        /// <param name="key">Key generated by Play method</param>
        /// <param name="clearParticles">Whether to use Clear() particles method</param>
        void Stop(long key, bool clearParticles = true);
        
        void StopAll(IVfx vfx);

        void DisposePool(IVfx vfx);
    }
}
